export const strings = {
  editProductTitle: 'Editar Producto',
  idLabel: 'ID',
  nameLabel: 'Nombre',
  namePlaceholder: 'Nombre del producto',
  descriptionLabel: 'Descripción',
  descriptionPlaceholder: 'Descripción del producto',
  logoLabel: 'Logo',
  logoPlaceholder: 'URL del logo',
  dateReleaseLabel: 'Fecha de Liberación',
  dateRevisionLabel: 'Fecha de Revisión',
  saveButton: 'Guardar Cambios',
  successTitle: 'Éxito',
  successMessage: 'Producto actualizado exitosamente',
  errorTitle: 'Error',
  errorMessage: 'No se pudo actualizar el producto',
};
