export const strings = {
  formTitle: 'Formulario de Registro',
  idLabel: 'ID',
  idPlaceholder: 'ID',
  nameLabel: 'Nombre',
  namePlaceholder: 'Nombre',
  descriptionLabel: 'Descripción',
  descriptionPlaceholder: 'Descripción',
  logoLabel: 'Logo',
  logoPlaceholder: 'URL del logo',
  dateReleaseLabel: 'Fecha de Liberación',
  dateRevisionLabel: 'Fecha de Revisión',
  submitButton: 'Enviar',
  resetButton: 'Reiniciar',
  successTitle: 'Éxito',
  successMessage: 'Producto agregado exitosamente',
  errorTitle: 'Error',
  errorMessage: 'No se pudo agregar el producto',
};
